# Generated by Django 5.0.4 on 2024-04-15 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='wishes',
            fields=[
                ('wish_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='wishes_to_implements',
            fields=[
                ('wish_to_implementer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('implementer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.users')),
                ('wish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.wishes')),
            ],
        ),
    ]
