# Generated by Django 5.0.4 on 2024-04-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='wishes',
            options={'verbose_name': 'Идея', 'verbose_name_plural': 'Идеи'},
        ),
        migrations.AlterModelOptions(
            name='wishes_to_implements',
            options={'verbose_name': 'Идея-Реализатор', 'verbose_name_plural': 'Идеи-Реализаторы'},
        ),
        migrations.AlterField(
            model_name='wishes_to_implements',
            name='implementer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.users', verbose_name='Идентификатор пользователя-реализатора'),
        ),
        migrations.AlterField(
            model_name='wishes_to_implements',
            name='wish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.wishes', verbose_name='Идентификатор идеи'),
        ),
    ]
