# Generated by Django 5.0.4 on 2024-05-08 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_users_options_alter_wishes_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishes_to_implements',
            name='implementer_id',
        ),
        migrations.AddField(
            model_name='wishes_to_implements',
            name='implementer_username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-реализатор'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
